<?php
return [
    'states' => [
        '01' => ['name' => 'Jammu & Kashmir',                      'is_ut' => true,  'ut_legislature' => true],
        '02' => ['name' => 'Himachal Pradesh',                     'is_ut' => false, 'ut_legislature' => false],
        '03' => ['name' => 'Punjab',                               'is_ut' => false, 'ut_legislature' => false],
        '04' => ['name' => 'Chandigarh',                           'is_ut' => true,  'ut_legislature' => false],
        '05' => ['name' => 'Uttarakhand',                          'is_ut' => false, 'ut_legislature' => false],
        '06' => ['name' => 'Haryana',                              'is_ut' => false, 'ut_legislature' => false],
        '07' => ['name' => 'Delhi',                                'is_ut' => true,  'ut_legislature' => true],
        '08' => ['name' => 'Rajasthan',                            'is_ut' => false, 'ut_legislature' => false],
        '09' => ['name' => 'Uttar Pradesh',                        'is_ut' => false, 'ut_legislature' => false],
        '10' => ['name' => 'Bihar',                                'is_ut' => false, 'ut_legislature' => false],
        '11' => ['name' => 'Sikkim',                               'is_ut' => false, 'ut_legislature' => false],
        '12' => ['name' => 'Arunachal Pradesh',                    'is_ut' => false, 'ut_legislature' => false],
        '13' => ['name' => 'Nagaland',                             'is_ut' => false, 'ut_legislature' => false],
        '14' => ['name' => 'Manipur',                              'is_ut' => false, 'ut_legislature' => false],
        '15' => ['name' => 'Mizoram',                              'is_ut' => false, 'ut_legislature' => false],
        '16' => ['name' => 'Tripura',                              'is_ut' => false, 'ut_legislature' => false],
        '17' => ['name' => 'Meghalaya',                            'is_ut' => false, 'ut_legislature' => false],
        '18' => ['name' => 'Assam',                                'is_ut' => false, 'ut_legislature' => false],
        '19' => ['name' => 'West Bengal',                          'is_ut' => false, 'ut_legislature' => false],
        '20' => ['name' => 'Jharkhand',                            'is_ut' => false, 'ut_legislature' => false],
        '21' => ['name' => 'Odisha',                               'is_ut' => false, 'ut_legislature' => false],
        '22' => ['name' => 'Chhattisgarh',                         'is_ut' => false, 'ut_legislature' => false],
        '23' => ['name' => 'Madhya Pradesh',                       'is_ut' => false, 'ut_legislature' => false],
        '24' => ['name' => 'Gujarat',                              'is_ut' => false, 'ut_legislature' => false],
        '25' => ['name' => 'Daman & Diu',                          'is_ut' => true,  'ut_legislature' => false],
        '26' => ['name' => 'Dadra & Nagar Haveli and Daman & Diu', 'is_ut' => true,  'ut_legislature' => false],
        '27' => ['name' => 'Maharashtra',                          'is_ut' => false, 'ut_legislature' => false],
        '28' => ['name' => 'Andhra Pradesh',                       'is_ut' => false, 'ut_legislature' => false],
        '29' => ['name' => 'Karnataka',                            'is_ut' => false, 'ut_legislature' => false],
        '30' => ['name' => 'Goa',                                  'is_ut' => false, 'ut_legislature' => false],
        '31' => ['name' => 'Lakshadweep',                          'is_ut' => true,  'ut_legislature' => false],
        '32' => ['name' => 'Kerala',                               'is_ut' => false, 'ut_legislature' => false],
        '33' => ['name' => 'Tamil Nadu',                           'is_ut' => false, 'ut_legislature' => false],
        '34' => ['name' => 'Puducherry',                           'is_ut' => true,  'ut_legislature' => true],
        '35' => ['name' => 'Andaman & Nicobar Islands',            'is_ut' => true,  'ut_legislature' => false],
        '36' => ['name' => 'Telangana',                            'is_ut' => false, 'ut_legislature' => false],
        '37' => ['name' => 'Andhra Pradesh (new)',                 'is_ut' => false, 'ut_legislature' => false],
        '38' => ['name' => 'Ladakh',                               'is_ut' => true,  'ut_legislature' => false],
        '96' => ['name' => 'Foreign',                              'is_ut' => false, 'ut_legislature' => false],
        '97' => ['name' => 'Other Territory',                      'is_ut' => true,  'ut_legislature' => false],
        '99' => ['name' => 'Centre',                               'is_ut' => false, 'ut_legislature' => false],
    ],
    'state_abbreviations' => [
        'ap'  => '37', 'andhra' => '37', 'andhra pradesh' => '37',
        'ar'  => '12', 'arunachal' => '12', 'arunachal pradesh' => '12',
        'as'  => '18', 'assam' => '18',
        'br'  => '10', 'bihar' => '10',
        'cg'  => '22', 'chattisgarh' => '22', 'chhattisgarh' => '22',
        'ch'  => '04', 'chandigarh' => '04',
        'dl'  => '07', 'delhi' => '07', 'ncr' => '07', 'new delhi' => '07',
        'ga'  => '30', 'goa' => '30',
        'gj'  => '24', 'gujarat' => '24',
        'hp'  => '02', 'himachal' => '02', 'himachal pradesh' => '02',
        'hr'  => '06', 'haryana' => '06',
        'jh'  => '20', 'jharkhand' => '20',
        'jk'  => '01', 'jammu' => '01', 'kashmir' => '01', 'jammu & kashmir' => '01', 'jammu and kashmir' => '01',
        'ka'  => '29', 'karnataka' => '29',
        'kl'  => '32', 'kerala' => '32',
        'la'  => '38', 'ladakh' => '38',
        'ld'  => '31', 'lakshadweep' => '31',
        'mh'  => '27', 'maharashtra' => '27',
        'ml'  => '17', 'meghalaya' => '17',
        'mn'  => '14', 'manipur' => '14',
        'mp'  => '23', 'madhya pradesh' => '23',
        'mz'  => '15', 'mizoram' => '15',
        'nl'  => '13', 'nagaland' => '13',
        'or'  => '21', 'od' => '21', 'odisha' => '21', 'orissa' => '21',
        'pb'  => '03', 'punjab' => '03',
        'py'  => '34', 'puducherry' => '34', 'pondicherry' => '34',
        'rj'  => '08', 'rajasthan' => '08',
        'sk'  => '11', 'sikkim' => '11',
        'tg'  => '36', 'ts' => '36', 'telangana' => '36',
        'tn'  => '33', 'tamil nadu' => '33', 'tamilnadu' => '33',
        'tr'  => '16', 'tripura' => '16',
        'uk'  => '05', 'ua' => '05', 'uttarakhand' => '05', 'uttaranchal' => '05',
        'up'  => '09', 'uttar pradesh' => '09',
        'wb'  => '19', 'west bengal' => '19',
        'an'  => '35', 'andaman' => '35', 'andaman & nicobar' => '35', 'andaman and nicobar' => '35',
        'dd'  => '26', 'daman' => '26', 'dadra' => '26',
    ],
];
